server:
  port: 30003
  servlet:
    context-path:
#  tomcat:
#    uri-encoding: UTF-8
#    basedir: /Users/liugf
#    max-threads: 2000
#    min-spare-threads: 10
#    accesslog:
#      pattern: common
#      enabled: true
#      directory: logs
#      prefix: jeeplus_access_log
#      suffix: .log
#      request-attributes-enabled: true
#      rename-on-rotate: true
logging:
  level:
    root: error
    #    org.flowable: DEBUG
    com.jeeplus: error
    org.apache.shiro.cache.ehcache.EhCacheManager: error
spring:
  servlet:
    multipart:
      maxFileSize:  1000MB
      maxRequestSize: 1000MB
  devtools:
    restart:
      enabled: true
  #  profiles:
  #    active: dev
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  #  jpa:
  #    open-in-view: false
  datasource:
    dynamic:
      druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        validation-query: select 'x' from dual
        SelectMethod: cursor
        filters: stat # 注意这个值和druid原生不一致，默认启动了stat,wall
      p6spy: false # 默认false,线上必须关闭。开发阶段可以打开调试输出mybatis语句，但是有许多莫名其妙的bug，以及严重的性能问题，所以正式环境必须关闭。
      datasource:
        master:
          username: sckr
          password: Sckr_2002
          url: jdbc:mysql://120.79.49.120:30002/cppcc?useUnicode=true&characterEncoding=utf-8&useSSL=false&nullCatalogMeansCurrent=true&serverTimezone=GMT&allowPublicKeyRetrieval=true
          # username: sckr
          #password: root
          #          url: jdbc:mysql://192.168.7.211:3306/cppcc?useUnicode=true&characterEncoding=utf-8&useSSL=false&nullCatalogMeansCurrent=true&serverTimezone=GMT
          #url: jdbc:mysql://127.0.0.1:3336/jeeplus?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT&nullCatalogMeansCurrent=true
          driver-class-name: com.mysql.cj.jdbc.Driver

          #oracle database settings
          #            username: monitor
          #            password: monitor
          #            url: jdbc:oracle:thin:@127.0.0.1:1521:helowin
          #            driver-class-name: oracle.jdbc.driver.OracleDriver


          ##mssql database settings
          #            username: sa
          #            password: yourStrong(!)Password
          #            driver-class-name: net.sourceforge.jtds.jdbc.Driver
          #            url: jdbc:jtds:sqlserver://localhost:1433;SelectMethod=cursor;DatabaseName=jeeplus
          #            SelectMethod: cursor
          #            testSql: SELECT 'x'


          ##pg database settings
  #            username: postgres
  #            password: password
  #            driver-class-name: org.postgresql.Driver
  #            url: jdbc:postgresql://localhost:5432/jeeplus-boot-pg
  #            testSql: SELECT 'x'
  # if you need use pg database , please enable this config.
  #  jpa:
  #    properties:
  #      hibernate:
  #        jdbc:
  #          lob:
  #            non_contextual_creation: true
  #spring-ehcache的配置
  cache:
    type: ehcache # redis/ehcache， 在这里设置你使用的缓存框架，如果不想使用redis，请改成ehcache
  ehcache:
    config: classpath:ehcache.xml
  redis:
    host: localhost
    port: 6379
    expireTime: 3600000 #单位秒
  mvc.servlet.load-on-startup: 1
  jmx:
    enabled: false
  # quartz任务配置
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            selectWithLockSQL: SELECT * FROM {0}LOCKS UPDLOCK WHERE LOCK_NAME = ?
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            tablePrefix: QRTZ_
            isClustered: false # 打开集群配置
            clusterCheckinInterval: 2000 # 设置集群检查间隔20s
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
flowable:
  # 关闭定时任务Job
  async-executor-activate: false
  check-process-definitions: false
  process-definition-location-prefix: classpath:/processes/
  database-schema-update: false
  common:
    app:
      idm-url: http://localhost:9999
      idm-admin:
        user: admin
        password: test
#mybatis的配置
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations:
    - classpath*:com/jeeplus/modules/**/*Mapper.xml
    - classpath:/META-INF/admin-mybatis-mappings/*.xml
    - classpath:/META-INF/modeler-mybatis-mappings/*.xml
  type-aliases-package: com.jeeplus.modules
  configuration-properties:
    prefix:
    boolValue: TRUE
    blobType: BLOB
#是否开启 swagger，生产环境请关闭
swagger:
  enable: false
#============================#
#===== System settings ======#
#============================#

#产品信息设置
copyrightYear: 2019
version: springboot2.0
#演示模式: 不能操作和保存的模块： sys
demoMode: false
#上传文件绝对路径, 路径中不允许包含“userfiles”
userfiles:
  basedir:  /opt/file     # 文件上传路径，可以留空
  allowedType: file  # 允许上传的文件类型， all, file ,image, audio, video, office
  extensions:
    all: all       # 允许上传所有类型文件
    file: 7z,aiff,asf,avi,bmp,csv,doc,docx,fla,flv,gif,gz,gzip,jpeg,jpg,mid,mov,mp3,mp4,mpc,mpeg,mpg,ods,odt,pdf,png,ppt,pptx,pxd,qt,ram,rar,rm,rmi,rmvb,rtf,sdc,sitd,swf,sxc,sxw,tar,tgz,tif,tiff,txt,vsd,wav,wma,wmv,xls,xlsx,zip       # 只允许上传安全文件（linux系统非可执行）
    image: gif,jpg,jpeg,bmp,png     # 只允许上传图片
    audio: CD,OGG,MP3,ASF,WMA,WAV,MP3PRO,RM,REAL,APE,MODULE,MIDI,VQF    # 只允许上传音频
    video: AVI,WMV,RM,RMVB,MPEG1,MPEG2,MPEG4(MP4),3GP,ASF,SWF,VOB,DAT,MOV,M4V,FLV,F4V,MKV,MTS,TS     # 只允许上传视频
    office: txt,xls,xlsx,xlsm,xltx,xltm,xlsb,xlam,doc,docx,docm,dotx,dotm,ppt,pptx,pptm,ppsx,ppsm,potx,potm,ppam     # 只允许上传office文件
#JWT access token过期时间（access过期时间，并不是指需要重新登录的超时时间，而是指需要刷新重新获取access token的时间，超时登录的时间是3*EXPIRE_TIME，即refresh token的有效时时间)
jwt.accessToken.expireTime: 86400000 # 24小时，单位毫秒


#===============================#
#====== license 信息 ================#
#===============================#

# 产品授权
productId: Y2021030525
license: 531E1A6B7E329457AF87E36F5568FCE64C4319EFDEF3B4D3150740F578A80DAA63E1BED1445B030C5A9C3D3BBDBA1476006D68C5239536714CAA91595E4AF440


#=======================================================================#
#===== plugin设置 =====#
#Plugin插件会读取该core和admin包下的基础类，如果修改了路径或者类名，请同步修改这里
#=======================================================================#
plugin:
  Page: com.jeeplus.core.persistence.Page
  User: com.jeeplus.modules.sys.entity.User
  Area: com.jeeplus.modules.sys.entity.Area
  Office: com.jeeplus.modules.sys.entity.Office
  UserUtils: com.jeeplus.modules.sys.utils.UserUtils

#===============================#
#====== 钉钉相关配置信息 flowable/task================#
#===============================#
ding:
  corp_id: ding6e8e480ff218ec6335c2f4657eb6378f
  agent_id: 1139796252
  app_key: ding7nzq0yfll4fwushp
  app_secret: KhzQ7fBo5bDMbc8-XTviaMa7ppozluVciHePVBXxiScTaVfhSRFVaVrS40hHWzPz
  web_path: "http://120.79.49.120:30003"